#!/usr/bin/env bash

if [ "x$(which node)" == "x" ]; then
  echo "node not found - please install nodejs for using speettest"
  exit -1
fi

/Users/dels/git/github/speedtest/cron.hourly/speedtest.js --execute -q

